"""Seed database with demo data for MediFlow AI."""

from datetime import datetime, date, timedelta
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from passlib.context import CryptContext
from database.models import User, HCP, Interaction, FollowUp, HCPTier, UserRole, InteractionType, Sentiment, FollowUpStatus, Priority

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")


async def seed_database(session: AsyncSession):
    """Seed all tables with realistic demo data."""
    existing = await session.execute(select(User).limit(1))
    if existing.scalar():
        return  # Already seeded

    # ── User ──
    user = User(
        email="rep@mediflow.ai",
        password_hash=pwd_context.hash("demo123"),
        full_name="John Carter",
        role=UserRole.REP,
        territory="Northeast",
        is_active=True,
    )
    session.add(user)
    await session.flush()

    # ── HCPs ──
    hcps_data = [
        {
            "name": "Dr. Sarah Chen",
            "specialty": "Cardiology",
            "institution": "Metro General Hospital",
            "city": "Boston",
            "state": "MA",
            "email": "s.chen@metrogeneral.org",
            "phone": "(617) 555-0101",
            "npi_number": "1234567890",
            "tier": HCPTier.A,
            "preferred_contact_method": "in-person",
            "relationship_score": 92.0,
            "engagement_data": {
                "visit_count": 7,
                "avg_sentiment": 0.88,
                "follow_up_completion_rate": 0.92,
                "last_product_discussed": "Cardiolex",
                "typical_objections": ["long-term side effects", "insurance coverage"],
                "buying_interest": "high",
                "engagement_trend": "growing",
            },
        },
        {
            "name": "Dr. James Williams",
            "specialty": "Neurology",
            "institution": "Northeast Medical Center",
            "city": "New York",
            "state": "NY",
            "email": "j.williams@nemc.org",
            "phone": "(212) 555-0202",
            "npi_number": "2345678901",
            "tier": HCPTier.A,
            "preferred_contact_method": "virtual",
            "relationship_score": 78.0,
            "engagement_data": {
                "visit_count": 5,
                "avg_sentiment": 0.72,
                "follow_up_completion_rate": 0.80,
                "last_product_discussed": "NeuroPro",
                "typical_objections": ["efficacy data", "patient compliance"],
                "buying_interest": "moderate",
                "engagement_trend": "stable",
            },
        },
        {
            "name": "Dr. Priya Patel",
            "specialty": "Oncology",
            "institution": "City Cancer Institute",
            "city": "Philadelphia",
            "state": "PA",
            "email": "p.patel@citycancer.org",
            "phone": "(215) 555-0303",
            "npi_number": "3456789012",
            "tier": HCPTier.A,
            "preferred_contact_method": "in-person",
            "relationship_score": 85.0,
            "engagement_data": {
                "visit_count": 6,
                "avg_sentiment": 0.82,
                "follow_up_completion_rate": 0.85,
                "last_product_discussed": "OncoShield",
                "typical_objections": ["cost", "clinical trial data"],
                "buying_interest": "high",
                "engagement_trend": "growing",
            },
        },
        {
            "name": "Dr. Michael Torres",
            "specialty": "Endocrinology",
            "institution": "Harbor Medical Group",
            "city": "Hartford",
            "state": "CT",
            "email": "m.torres@harbormed.org",
            "phone": "(860) 555-0404",
            "npi_number": "4567890123",
            "tier": HCPTier.B,
            "preferred_contact_method": "email",
            "relationship_score": 65.0,
            "engagement_data": {
                "visit_count": 3,
                "avg_sentiment": 0.60,
                "follow_up_completion_rate": 0.70,
                "last_product_discussed": "GlucoBalance",
                "typical_objections": ["competitor pricing", "dosage complexity"],
                "buying_interest": "moderate",
                "engagement_trend": "stable",
            },
        },
        {
            "name": "Dr. Emily Kim",
            "specialty": "Rheumatology",
            "institution": "Academic Medical Center",
            "city": "New Haven",
            "state": "CT",
            "email": "e.kim@amcenter.org",
            "phone": "(203) 555-0505",
            "npi_number": "5678901234",
            "tier": HCPTier.B,
            "preferred_contact_method": "in-person",
            "relationship_score": 71.0,
            "engagement_data": {
                "visit_count": 4,
                "avg_sentiment": 0.70,
                "follow_up_completion_rate": 0.75,
                "last_product_discussed": "FlexiJoint",
                "typical_objections": ["injection frequency", "patient tolerance"],
                "buying_interest": "moderate",
                "engagement_trend": "growing",
            },
        },
        {
            "name": "Dr. Robert Chang",
            "specialty": "Pulmonology",
            "institution": "Riverside Lung Center",
            "city": "Providence",
            "state": "RI",
            "email": "r.chang@riverside.org",
            "phone": "(401) 555-0606",
            "npi_number": "6789012345",
            "tier": HCPTier.B,
            "preferred_contact_method": "phone",
            "relationship_score": 58.0,
            "engagement_data": {
                "visit_count": 2,
                "avg_sentiment": 0.55,
                "follow_up_completion_rate": 0.60,
                "last_product_discussed": "BreatheEasy",
                "typical_objections": ["limited formulary access"],
                "buying_interest": "low",
                "engagement_trend": "declining",
            },
        },
        {
            "name": "Dr. Amanda Foster",
            "specialty": "Dermatology",
            "institution": "Skin Health Clinic",
            "city": "Stamford",
            "state": "CT",
            "email": "a.foster@skinhealth.com",
            "phone": "(203) 555-0707",
            "npi_number": "7890123456",
            "tier": HCPTier.C,
            "preferred_contact_method": "email",
            "relationship_score": 45.0,
            "engagement_data": {
                "visit_count": 1,
                "avg_sentiment": 0.50,
                "follow_up_completion_rate": 0.50,
                "last_product_discussed": "DermaShield",
                "typical_objections": ["already using competitor"],
                "buying_interest": "low",
                "engagement_trend": "stable",
            },
        },
        {
            "name": "Dr. David Nakamura",
            "specialty": "Gastroenterology",
            "institution": "Digestive Health Partners",
            "city": "Worcester",
            "state": "MA",
            "email": "d.nakamura@dhpartners.org",
            "phone": "(508) 555-0808",
            "npi_number": "8901234567",
            "tier": HCPTier.B,
            "preferred_contact_method": "in-person",
            "relationship_score": 69.0,
            "engagement_data": {
                "visit_count": 3,
                "avg_sentiment": 0.65,
                "follow_up_completion_rate": 0.80,
                "last_product_discussed": "GastroCalm",
                "typical_objections": ["need more real-world evidence"],
                "buying_interest": "moderate",
                "engagement_trend": "growing",
            },
        },
        {
            "name": "Dr. Lisa Okonkwo",
            "specialty": "Cardiology",
            "institution": "Heart & Vascular Institute",
            "city": "Newark",
            "state": "NJ",
            "email": "l.okonkwo@hvi.org",
            "phone": "(973) 555-0909",
            "npi_number": "9012345678",
            "tier": HCPTier.A,
            "preferred_contact_method": "in-person",
            "relationship_score": 80.0,
            "engagement_data": {
                "visit_count": 5,
                "avg_sentiment": 0.78,
                "follow_up_completion_rate": 0.88,
                "last_product_discussed": "Cardiolex",
                "typical_objections": ["comparative effectiveness"],
                "buying_interest": "high",
                "engagement_trend": "stable",
            },
        },
        {
            "name": "Dr. Steven Park",
            "specialty": "Psychiatry",
            "institution": "Behavioral Wellness Center",
            "city": "Albany",
            "state": "NY",
            "email": "s.park@bwcenter.org",
            "phone": "(518) 555-1010",
            "npi_number": "0123456789",
            "tier": HCPTier.C,
            "preferred_contact_method": "virtual",
            "relationship_score": 42.0,
            "engagement_data": {
                "visit_count": 1,
                "avg_sentiment": 0.45,
                "follow_up_completion_rate": 0.40,
                "last_product_discussed": "MindBalance",
                "typical_objections": ["patient reluctance", "side effect profile"],
                "buying_interest": "low",
                "engagement_trend": "declining",
            },
        },
        {
            "name": "Dr. Maria Gonzalez",
            "specialty": "Pediatrics",
            "institution": "Children's Regional Hospital",
            "city": "Springfield",
            "state": "MA",
            "email": "m.gonzalez@childrens.org",
            "phone": "(413) 555-1111",
            "npi_number": "1122334455",
            "tier": HCPTier.B,
            "preferred_contact_method": "in-person",
            "relationship_score": 73.0,
            "engagement_data": {
                "visit_count": 4,
                "avg_sentiment": 0.75,
                "follow_up_completion_rate": 0.82,
                "last_product_discussed": "PediaGrow",
                "typical_objections": ["pediatric dosing data"],
                "buying_interest": "moderate",
                "engagement_trend": "growing",
            },
        },
        {
            "name": "Dr. Thomas Reed",
            "specialty": "Orthopedics",
            "institution": "Sports Medicine Associates",
            "city": "Burlington",
            "state": "VT",
            "email": "t.reed@sportsmed.org",
            "phone": "(802) 555-1212",
            "npi_number": "2233445566",
            "tier": HCPTier.C,
            "preferred_contact_method": "phone",
            "relationship_score": 38.0,
            "engagement_data": {
                "visit_count": 1,
                "avg_sentiment": 0.40,
                "follow_up_completion_rate": 0.30,
                "last_product_discussed": "FlexiJoint",
                "typical_objections": ["prefers surgical approach"],
                "buying_interest": "low",
                "engagement_trend": "declining",
            },
        },
        {
            "name": "Dr. Rachel Hoffman",
            "specialty": "Nephrology",
            "institution": "Kidney Care Specialists",
            "city": "Portland",
            "state": "ME",
            "email": "r.hoffman@kidneycare.org",
            "phone": "(207) 555-1313",
            "npi_number": "3344556677",
            "tier": HCPTier.B,
            "preferred_contact_method": "virtual",
            "relationship_score": 67.0,
            "engagement_data": {
                "visit_count": 3,
                "avg_sentiment": 0.68,
                "follow_up_completion_rate": 0.78,
                "last_product_discussed": "RenalGuard",
                "typical_objections": ["renal dosing adjustments"],
                "buying_interest": "moderate",
                "engagement_trend": "stable",
            },
        },
        {
            "name": "Dr. Kevin O'Brien",
            "specialty": "Hematology",
            "institution": "Blood Disorders Center",
            "city": "Manchester",
            "state": "NH",
            "email": "k.obrien@bloodcenter.org",
            "phone": "(603) 555-1414",
            "npi_number": "4455667788",
            "tier": HCPTier.A,
            "preferred_contact_method": "in-person",
            "relationship_score": 88.0,
            "engagement_data": {
                "visit_count": 6,
                "avg_sentiment": 0.85,
                "follow_up_completion_rate": 0.90,
                "last_product_discussed": "HemaBoost",
                "typical_objections": ["monitoring requirements"],
                "buying_interest": "high",
                "engagement_trend": "growing",
            },
        },
        {
            "name": "Dr. Susan White",
            "specialty": "Allergy & Immunology",
            "institution": "Allergy Associates of New England",
            "city": "Concord",
            "state": "NH",
            "email": "s.white@allergyNE.org",
            "phone": "(603) 555-1515",
            "npi_number": "5566778899",
            "tier": HCPTier.C,
            "preferred_contact_method": "email",
            "relationship_score": 50.0,
            "engagement_data": {
                "visit_count": 2,
                "avg_sentiment": 0.55,
                "follow_up_completion_rate": 0.50,
                "last_product_discussed": "ImmunoShield",
                "typical_objections": ["small patient base for this indication"],
                "buying_interest": "low",
                "engagement_trend": "stable",
            },
        },
    ]

    hcp_objects = []
    for data in hcps_data:
        hcp = HCP(**data)
        session.add(hcp)
        hcp_objects.append(hcp)
    await session.flush()

    # ── Interactions ──
    today = date.today()
    interactions_data = [
        {
            "hcp_id": hcp_objects[0].id,  # Dr. Sarah Chen
            "user_id": user.id,
            "interaction_date": today,
            "interaction_type": InteractionType.IN_PERSON,
            "products_discussed": ["Cardiolex"],
            "key_topics": "Discussed Cardiolex for resistant hypertension management. Dr. Chen expressed strong interest in Phase III clinical trial results.",
            "sentiment": Sentiment.POSITIVE,
            "sentiment_score": 0.92,
            "ai_summary": "Productive in-person meeting with Dr. Chen at Metro General. Strong interest in Cardiolex for resistant HTN. Requested Phase III data and clinical trial results. Positive reception overall.",
            "ai_executive_summary": {
                "key_outcomes": ["Strong interest in Cardiolex confirmed", "Phase III data requested", "5 samples delivered"],
                "next_actions": ["Send clinical trial data via email", "Schedule product demonstration", "Follow up in 10 days"],
                "risks": ["Competitor drug recently launched in same space"],
            },
            "ai_confidence": 0.94,
            "entities_extracted": {
                "doctor": {"value": "Dr. Sarah Chen", "confidence": 0.98},
                "product": {"value": "Cardiolex", "confidence": 0.96},
                "sentiment": {"value": "positive", "confidence": 0.92},
                "follow_up": {"value": str(today + timedelta(days=10)), "confidence": 0.90},
            },
            "compliance_flags": {"status": "clean", "flags": []},
            "strategic_insight": "Dr. Chen has shown progressively increasing interest in Cardiolex over the last 3 meetings. Recommend scheduling a product demonstration to capitalize on momentum.",
            "notes": "Dropped 5 Cardiolex samples. Dr. Chen mentioned she's presenting at cardiology conference next month.",
            "samples_dropped": ["Cardiolex x5"],
            "duration_minutes": 35,
            "location": "Metro General Hospital, Cardiology Dept",
            "follow_up_date": today + timedelta(days=10),
            "follow_up_actions": "Send Phase III clinical trial data, schedule product demo",
        },
        {
            "hcp_id": hcp_objects[1].id,  # Dr. James Williams
            "user_id": user.id,
            "interaction_date": today - timedelta(days=1),
            "interaction_type": InteractionType.VIRTUAL,
            "products_discussed": ["NeuroPro"],
            "key_topics": "Follow-up on NeuroPro adoption discussion. Dr. Williams had questions about patient compliance data.",
            "sentiment": Sentiment.NEUTRAL,
            "sentiment_score": 0.55,
            "ai_summary": "Virtual follow-up with Dr. Williams regarding NeuroPro. Neutral reception — requesting more patient compliance and real-world evidence data before committing.",
            "ai_executive_summary": {
                "key_outcomes": ["Patient compliance concerns identified", "Requesting real-world evidence"],
                "next_actions": ["Compile patient compliance data", "Share post-market surveillance report"],
                "risks": ["May switch to competitor if data not provided soon"],
            },
            "ai_confidence": 0.88,
            "entities_extracted": {
                "doctor": {"value": "Dr. James Williams", "confidence": 0.97},
                "product": {"value": "NeuroPro", "confidence": 0.95},
                "sentiment": {"value": "neutral", "confidence": 0.82},
                "follow_up": {"value": str(today + timedelta(days=5)), "confidence": 0.85},
            },
            "compliance_flags": {"status": "clean", "flags": []},
            "strategic_insight": "Dr. Williams is in evaluation phase. Providing strong real-world evidence could tip the decision in our favor. Time-sensitive opportunity.",
            "notes": "30-minute video call. Will send compliance data by end of week.",
            "samples_dropped": [],
            "duration_minutes": 30,
            "location": "Virtual - Zoom",
            "follow_up_date": today + timedelta(days=5),
            "follow_up_actions": "Send patient compliance data and post-market surveillance report",
        },
        {
            "hcp_id": hcp_objects[2].id,  # Dr. Priya Patel
            "user_id": user.id,
            "interaction_date": today - timedelta(days=2),
            "interaction_type": InteractionType.IN_PERSON,
            "products_discussed": ["OncoShield"],
            "key_topics": "Discussed OncoShield for adjuvant therapy. Dr. Patel interested in combination therapy data.",
            "sentiment": Sentiment.POSITIVE,
            "sentiment_score": 0.85,
            "ai_summary": "Strong meeting with Dr. Patel at City Cancer Institute. High interest in OncoShield for adjuvant therapy. Wants combination therapy clinical data.",
            "ai_executive_summary": {
                "key_outcomes": ["Interest in OncoShield for adjuvant use confirmed", "Combination therapy data requested"],
                "next_actions": ["Email combination therapy trial results", "Arrange meeting with medical science liaison"],
                "risks": ["Cost concerns may be raised by hospital administration"],
            },
            "ai_confidence": 0.91,
            "entities_extracted": {
                "doctor": {"value": "Dr. Priya Patel", "confidence": 0.99},
                "product": {"value": "OncoShield", "confidence": 0.97},
                "sentiment": {"value": "positive", "confidence": 0.85},
                "follow_up": {"value": str(today + timedelta(days=7)), "confidence": 0.88},
            },
            "compliance_flags": {"status": "clean", "flags": []},
            "strategic_insight": "Dr. Patel is a key opinion leader in oncology. Securing her endorsement could influence adoption across the institute.",
            "notes": "Dr. Patel mentioned upcoming tumor board meeting where she could present OncoShield data.",
            "samples_dropped": ["OncoShield informational kit x1"],
            "duration_minutes": 45,
            "location": "City Cancer Institute, Conference Room B",
            "follow_up_date": today + timedelta(days=7),
            "follow_up_actions": "Email combination therapy data, coordinate MSL meeting",
        },
        {
            "hcp_id": hcp_objects[0].id,  # Dr. Sarah Chen (older visit)
            "user_id": user.id,
            "interaction_date": today - timedelta(days=7),
            "interaction_type": InteractionType.IN_PERSON,
            "products_discussed": ["Cardiolex"],
            "key_topics": "Initial discussion about Cardiolex mechanism of action. Dr. Chen was curious but cautious.",
            "sentiment": Sentiment.NEUTRAL,
            "sentiment_score": 0.60,
            "ai_summary": "First detailed discussion about Cardiolex with Dr. Chen. She's interested in the mechanism of action but wants to see more data before prescribing.",
            "ai_executive_summary": {
                "key_outcomes": ["Initial awareness of Cardiolex established", "MOA discussion went well"],
                "next_actions": ["Prepare efficacy comparison data", "Schedule follow-up in 1 week"],
                "risks": ["Currently prescribing competitor product"],
            },
            "ai_confidence": 0.87,
            "entities_extracted": {
                "doctor": {"value": "Dr. Sarah Chen", "confidence": 0.98},
                "product": {"value": "Cardiolex", "confidence": 0.94},
                "sentiment": {"value": "neutral", "confidence": 0.78},
                "follow_up": {"value": str(today), "confidence": 0.82},
            },
            "compliance_flags": {"status": "clean", "flags": []},
            "strategic_insight": "Dr. Chen is warming up to Cardiolex but needs data-driven persuasion. Focus next visit on efficacy comparisons.",
            "notes": None,
            "samples_dropped": ["Cardiolex x3"],
            "duration_minutes": 25,
            "location": "Metro General Hospital",
            "follow_up_date": today,
            "follow_up_actions": "Bring efficacy comparison data",
        },
        {
            "hcp_id": hcp_objects[3].id,  # Dr. Michael Torres
            "user_id": user.id,
            "interaction_date": today - timedelta(days=3),
            "interaction_type": InteractionType.PHONE,
            "products_discussed": ["GlucoBalance"],
            "key_topics": "Brief check-in about GlucoBalance trial samples. Dr. Torres mentioned patient feedback has been mixed.",
            "sentiment": Sentiment.NEUTRAL,
            "sentiment_score": 0.50,
            "ai_summary": "Phone check-in with Dr. Torres regarding GlucoBalance samples. Mixed patient feedback reported. Needs more evidence to continue prescribing.",
            "ai_executive_summary": {
                "key_outcomes": ["Mixed patient feedback on GlucoBalance noted", "Continued evaluation in progress"],
                "next_actions": ["Send additional patient outcome data", "Offer to arrange peer-to-peer discussion"],
                "risks": ["May discontinue if patient feedback doesn't improve"],
            },
            "ai_confidence": 0.83,
            "entities_extracted": {
                "doctor": {"value": "Dr. Michael Torres", "confidence": 0.96},
                "product": {"value": "GlucoBalance", "confidence": 0.93},
                "sentiment": {"value": "neutral", "confidence": 0.75},
                "follow_up": {"value": str(today + timedelta(days=14)), "confidence": 0.80},
            },
            "compliance_flags": {"status": "clean", "flags": []},
            "strategic_insight": "Dr. Torres needs reassurance through peer validation. A peer-to-peer discussion with a satisfied prescriber could be effective.",
            "notes": "15-minute call. Dr. Torres seemed distracted.",
            "samples_dropped": [],
            "duration_minutes": 15,
            "location": "Phone",
            "follow_up_date": today + timedelta(days=14),
            "follow_up_actions": "Send patient outcome data, arrange peer-to-peer call",
        },
        {
            "hcp_id": hcp_objects[4].id,  # Dr. Emily Kim
            "user_id": user.id,
            "interaction_date": today - timedelta(days=5),
            "interaction_type": InteractionType.IN_PERSON,
            "products_discussed": ["FlexiJoint"],
            "key_topics": "Discussed FlexiJoint for RA patients. Positive reception to new injection protocol.",
            "sentiment": Sentiment.POSITIVE,
            "sentiment_score": 0.80,
            "ai_summary": "Met with Dr. Kim at Academic Medical Center. Positive response to FlexiJoint's new bi-weekly injection protocol. Reduced frequency addresses her main concern.",
            "ai_executive_summary": {
                "key_outcomes": ["New injection protocol well received", "Addresses prior patient tolerance concern"],
                "next_actions": ["Send updated protocol documentation", "Provide patient starter kits"],
                "risks": ["Competing product launching next quarter"],
            },
            "ai_confidence": 0.89,
            "entities_extracted": {
                "doctor": {"value": "Dr. Emily Kim", "confidence": 0.97},
                "product": {"value": "FlexiJoint", "confidence": 0.95},
                "sentiment": {"value": "positive", "confidence": 0.80},
                "follow_up": {"value": str(today + timedelta(days=12)), "confidence": 0.86},
            },
            "compliance_flags": {"status": "clean", "flags": []},
            "strategic_insight": "Dr. Kim's main objection (injection frequency) has been resolved. Strike while the iron is hot — provide starter kits this week.",
            "notes": None,
            "samples_dropped": ["FlexiJoint starter kit x2"],
            "duration_minutes": 30,
            "location": "Academic Medical Center",
            "follow_up_date": today + timedelta(days=12),
            "follow_up_actions": "Send protocol documentation, deliver patient starter kits",
        },
        {
            "hcp_id": hcp_objects[8].id,  # Dr. Lisa Okonkwo
            "user_id": user.id,
            "interaction_date": today - timedelta(days=4),
            "interaction_type": InteractionType.IN_PERSON,
            "products_discussed": ["Cardiolex"],
            "key_topics": "Discussed Cardiolex comparative data vs current standard of care. Dr. Okonkwo interested but wants head-to-head trial results.",
            "sentiment": Sentiment.POSITIVE,
            "sentiment_score": 0.78,
            "ai_summary": "Good meeting with Dr. Okonkwo at Heart & Vascular Institute. Interest in Cardiolex contingent on head-to-head comparison data.",
            "ai_executive_summary": {
                "key_outcomes": ["Interest in Cardiolex confirmed", "Head-to-head data is key decision factor"],
                "next_actions": ["Compile head-to-head comparison data", "Schedule follow-up presentation"],
                "risks": ["Current standard of care is deeply entrenched"],
            },
            "ai_confidence": 0.90,
            "entities_extracted": {
                "doctor": {"value": "Dr. Lisa Okonkwo", "confidence": 0.98},
                "product": {"value": "Cardiolex", "confidence": 0.96},
                "sentiment": {"value": "positive", "confidence": 0.78},
                "follow_up": {"value": str(today + timedelta(days=8)), "confidence": 0.84},
            },
            "compliance_flags": {"status": "clean", "flags": []},
            "strategic_insight": "Dr. Okonkwo values evidence-based decisions. Presenting strong head-to-head data could convert her to an advocate.",
            "notes": None,
            "samples_dropped": ["Cardiolex x3"],
            "duration_minutes": 40,
            "location": "Heart & Vascular Institute",
            "follow_up_date": today + timedelta(days=8),
            "follow_up_actions": "Prepare head-to-head comparison presentation",
        },
        {
            "hcp_id": hcp_objects[13].id,  # Dr. Kevin O'Brien
            "user_id": user.id,
            "interaction_date": today - timedelta(days=6),
            "interaction_type": InteractionType.IN_PERSON,
            "products_discussed": ["HemaBoost"],
            "key_topics": "Follow-up on HemaBoost adoption. Dr. O'Brien has started prescribing for select patients. Very positive feedback.",
            "sentiment": Sentiment.POSITIVE,
            "sentiment_score": 0.92,
            "ai_summary": "Excellent follow-up with Dr. O'Brien. HemaBoost adoption underway — prescribing for select patients with very positive results. Strong advocate.",
            "ai_executive_summary": {
                "key_outcomes": ["Active prescribing confirmed", "Positive patient outcomes reported", "Potential KOL advocate"],
                "next_actions": ["Invite to advisory board", "Request testimonial for case study"],
                "risks": ["Monitoring protocol complexity may limit broader adoption"],
            },
            "ai_confidence": 0.93,
            "entities_extracted": {
                "doctor": {"value": "Dr. Kevin O'Brien", "confidence": 0.99},
                "product": {"value": "HemaBoost", "confidence": 0.97},
                "sentiment": {"value": "positive", "confidence": 0.92},
                "follow_up": {"value": str(today + timedelta(days=15)), "confidence": 0.88},
            },
            "compliance_flags": {"status": "clean", "flags": []},
            "strategic_insight": "Dr. O'Brien is emerging as a key advocate for HemaBoost. Consider inviting him to the advisory board to deepen engagement.",
            "notes": "Dr. O'Brien enthusiastic about patient outcomes. Potential for case study collaboration.",
            "samples_dropped": ["HemaBoost x10"],
            "duration_minutes": 35,
            "location": "Blood Disorders Center",
            "follow_up_date": today + timedelta(days=15),
            "follow_up_actions": "Send advisory board invitation, discuss case study opportunity",
        },
    ]

    interaction_objects = []
    for data in interactions_data:
        interaction = Interaction(**data)
        session.add(interaction)
        interaction_objects.append(interaction)
    await session.flush()

    # ── Follow-Ups ──
    follow_ups_data = [
        {
            "interaction_id": interaction_objects[0].id,
            "hcp_id": hcp_objects[0].id,  # Dr. Chen
            "user_id": user.id,
            "due_date": today + timedelta(days=1),
            "action_description": "Send Phase III clinical trial data for Cardiolex",
            "ai_suggested_actions": [
                "Email Phase III clinical trial PDF",
                "Include efficacy comparison chart",
                "Mention upcoming cardiology conference presentation",
            ],
            "status": FollowUpStatus.PENDING,
            "priority": Priority.HIGH,
        },
        {
            "interaction_id": interaction_objects[1].id,
            "hcp_id": hcp_objects[1].id,  # Dr. Williams
            "user_id": user.id,
            "due_date": today - timedelta(days=1),  # Overdue
            "action_description": "Send NeuroPro patient compliance data",
            "ai_suggested_actions": [
                "Compile 6-month compliance report",
                "Include patient satisfaction survey results",
                "Offer peer-to-peer discussion with Dr. Chen",
            ],
            "status": FollowUpStatus.OVERDUE,
            "priority": Priority.HIGH,
        },
        {
            "interaction_id": interaction_objects[2].id,
            "hcp_id": hcp_objects[2].id,  # Dr. Patel
            "user_id": user.id,
            "due_date": today + timedelta(days=3),
            "action_description": "Email OncoShield combination therapy data",
            "ai_suggested_actions": [
                "Send combination therapy trial results",
                "Coordinate MSL meeting for technical deep-dive",
                "Provide tumor board presentation template",
            ],
            "status": FollowUpStatus.PENDING,
            "priority": Priority.MEDIUM,
        },
        {
            "interaction_id": interaction_objects[3].id,
            "hcp_id": hcp_objects[0].id,  # Dr. Chen - older
            "user_id": user.id,
            "due_date": today - timedelta(days=2),  # Overdue
            "action_description": "Bring efficacy comparison data for Cardiolex",
            "ai_suggested_actions": [
                "Print comparison charts",
                "Prepare competitor analysis slide",
            ],
            "status": FollowUpStatus.OVERDUE,
            "priority": Priority.MEDIUM,
        },
        {
            "interaction_id": interaction_objects[5].id,
            "hcp_id": hcp_objects[4].id,  # Dr. Kim
            "user_id": user.id,
            "due_date": today + timedelta(days=7),
            "action_description": "Deliver FlexiJoint patient starter kits",
            "ai_suggested_actions": [
                "Deliver 5 patient starter kits",
                "Include updated injection protocol guide",
                "Schedule 2-week check-in call",
            ],
            "status": FollowUpStatus.PENDING,
            "priority": Priority.LOW,
        },
    ]

    for data in follow_ups_data:
        follow_up = FollowUp(**data)
        session.add(follow_up)

    await session.commit()
